import React from "react";
import type {Metadata} from "next";
import localFont from "next/font/local";
import "../shared/globals.css";

const sfPro = localFont({
  src: "../shared/fonts/SF-Pro-Display-Regular.otf"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={sfPro.className}>
    <head>
      <meta charSet="utf-8"/>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
      <title>My app</title>
    </head>
    <body
      className={"font-[sf{ro] "}
    >
    {children}
    </body>
    </html>
  );
}
